"""create contact and message tables

Revision ID: 74a46d28dbc8
Revises: 
Create Date: 2026-08-02 08:09:04.279201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a46d28dbc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.Enum('in', 'out', name='message_direction', native_enum=False), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_contact_id_created_at', 'message', ['contact_id', 'created_at'], unique=False)
    op.create_index('uq_message_provider_message_id', 'message', ['provider_message_id'], unique=True, postgresql_where=sa.text('provider_message_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_message_provider_message_id', table_name='message', postgresql_where=sa.text('provider_message_id IS NOT NULL'))
    op.drop_index('ix_message_contact_id_created_at', table_name='message')
    op.drop_table('message')
    op.drop_table('contact')
    # ### end Alembic commands ###
